config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root to: "products#index"

    get "sign_in", to: "sessions#new"
    post "sign_in", to: "sessions#create"
    delete "sign_out", to: "sessions#destroy"

    resources :products, only: [:index, :show]
    resources :orders, only: [:new, :create]
    resources :carts, only: [:index, :create, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :parent, class_name: name, optional: true
  has_many :products, dependent: :destroy
  has_many :childrens,
           class_name: name,
           foreign_key: :parent_id,
           dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
  has_many :products, through: :order_details

  enum status: {
    pending: "pending",
    approved: "approved",
    rejected: "rejected",
    cancel: "cancel",
    moving: "moving",
    done: "done"
  }

  enum method_payment: {
    cod: "cod",
    credit: "credit",
    debit: "debit",
    paypal: "paypal"
  }

  def total
    order_details.map do |order_item|
      order_item.valid? ? order_item.total : 0
    end.sum
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :update_current_price

  def total
    current_price * quantity
  end

  private

  def update_current_price
    self.current_price = product.price
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :ratings, dependent: :destroy
  has_many :users, through: :ratings
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details

  scope :newest, ->{order created_at: :desc}
  scope :load_cart, ->(id){where id: id}

  def change_inventory type, value
    increment :inventory_count, value if type.eql? "add"

    if (type.eql? "sub") && (inventory_count - value >= 0)
      decrement :inventory_count, value
    end

    save!
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ratings, dependent: :destroy
  has_many :products, through: :ratings
  has_many :orders, dependent: :destroy

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  before_action :set_locale
  before_action :init_cart

  add_flash_types :error

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end

  def init_cart
    session[:cart] ||= {}
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :product_correct, only: [:create, :destroy, :update]
  before_action :load_products_in_cart, only: [:index, :update]
  before_action :load_total, only: [:index, :update]

  def index; end

  def create
    @id = params[:id]
    session[:cart][@id] = 1 unless product_in_cart? @id
    flash.now[:notice] = t ".add_success"

    respond_to do |format|
      format.js
    end
  end

  def update
    id = params[:id]
    value = params[:value].to_i
    return if value <= 0

    session[:cart][id] = value if product_in_cart? id
    total_item = @product.price * session[:cart][id]

    respond_to do |format|
      format.json do
        render json: {
          amount: amount_product,
          total_item: total_item,
          total: @total
        }
      end
    end
  end

  def destroy
    @id = params[:id]
    session[:cart].delete(@id)

    respond_to do |format|
      format.js
    end
  end

  private

  def product_correct
    @product = Product.find_by id: params[:id].to_i
    return if @product

    redirect_to root_path, alert: t(".product_not_valid")
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :require_logged_in, only: [:new]
  before_action :load_products_in_cart, only: [:new]
  before_action :load_total, only: [:new]

  def new; end

  def create
    ActiveRecord::Base.transaction do
      order = current_user.orders.create!(order_params)
      order_details = order.order_details.build load_order_details
      save_order_details order_details

      session[:cart] = {}
      redirect_to root_path, notice: t(".create_order_success")
    rescue ActiveRecord::RecordInvalid
      redirect_to new_order_path, error: t(".create_order_error")
    end
  end

  private

  def save_order_details order_details
    order_details.each do |order_detail|
      order_detail.save!
      order_detail.product.change_inventory "sub", order_detail.quantity
    end
  end

  def order_params
    return if params[:another_address].eql? "0"

    params.permit(:name_receive, :address_receive, :phone_recieve, :note)
  end

  def load_order_details
    session[:cart].map{|key, value| {product_id: key.to_i, quantity: value}}
  end

  def require_logged_in
    return if session[:user_id].present?

    store_location
    redirect_to sign_in_path, alert: t(".required_sign_in")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, only: [:show]

  def index
    @products = Product.newest.paginate(
      page: params[:page],
      per_page: Settings.products.paginate.per_page
    )
  end

  def show; end

  private

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product

    render file: Rails.root.join("public", "404.html"), layout: false, status:
      :not_found
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :find_user, only: [:create]

  def new
    redirect_to root_path if current_user.present?
  end

  def create
    if @user.authenticate params[:password]
      handle_actived
    else
      flash.now[:error] = t ".invalid_email_password"
      render :new
    end
  end

  def destroy
    session.delete :user_id
    @current_user = nil
    redirect_to root_path
  end

  private

  def handle_actived
    if @user.actived
      session[:user_id] = @user.id
      redirect_back_or root_path, t(".logged_success")
    else
      flash[:alert] = t ".account_not_actived"
      render :new
    end
  end

  def find_user
    @user = User.find_by email: params[:email]
    return if @user

    flash.now[:error] = t ".invalid_email_password"
    render :new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_currency price
    number_to_currency price, precision: 0
  end
end

app/helpers/product_helper.rb
module ProductHelper
  def product_empty product
    product.inventory_count.eql? 0
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    current_user.present?
  end

  def current_user
    session[:user_id] && @current_user = User.find_by(id: session[:user_id])
  end

  def amount_product
    session[:cart].values.sum
  end

  def product_in_cart? id
    session[:cart].keys.include? id.to_s
  end

  def redirect_back_or default, message
    redirect_to session[:forwarding_url],
                notice: (message unless message.empty?) || default
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

  def load_products_in_cart
    filter_attributes = [:id, :name, :price, :inventory_count]
    @products = Product.load_cart(session[:cart].keys).select(filter_attributes)
  end

  def load_total
    return 0 unless @products

    @total = @products.reduce(0) do |sum, product|
      sum + product.price * session[:cart][product.id.to_s]
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/carts/_add_to_cart.html.erb
<% if product_in_cart? @product.id %>
  <%= link_to t(".go_to_cart"), carts_path, class:"btn btn-secondary" %>
<% else %>
  <%= button_to t(".add_to_cart"), carts_path(id: @product.id), {
    remote: true,
    class: "btn btn-primary"
  } %>
  <% end %>

app/views/carts/_empty_cart.html.erb
<div class="col text-center">
  <h4 class="mb-4"><%= t ".cart_empty" %></h4>
  <%= link_to root_path, class:"btn btn-primary" do %>
    <i class="fas fa-chevron-left"></i> <%= t ".go_to_shop" %>
  <% end %>
</div>

app/views/carts/_product.html.erb
<% id, name, price, inventory_count = product.values_at(:id, :name, :price, :inventory_count) %>

<tr id=<%= "cart-item-#{id}" %>>
  <td>
    <img src="https://picsum.photos/200/300"
      alt="image"
      class="form-control"
      style="height: 150px; width: 100%; object-fit: cover;"
    />
  </td>
  <td><span class="form-control" name="name"><%= name %></span></td>
  <td><span class="form-control" name="price"><%= format_currency price %></span></td>
  <td><%= number_field_tag "cart-item-quantity-#{id}", session[:cart][id.to_s], {
      in: 1..inventory_count,
      "data-id":  "#{id}",
      "data-action": "carts/#{id}",
      class: "form-control"
    } %>
  </td>
  <td>
    <span class="form-control" id="total-item-<%= id %>">
      <%= format_currency price * session[:cart][id.to_s] %>
    </span>
  </td>
  <td>
    <%= button_to cart_path(id: id), {
      method: :delete,
      remote: true,
      class: "btn btn-danger"
    } do %>
    <i class="fas fa-trash"></i>
  <% end %>
  </td>
</tr>

app/views/carts/create.js.erb
$('#flash-messages').html("<%= j render 'shared/flash' %>")
$('#nav-buttons').html("<%= j render partial: 'carts/add_to_cart', locals: {id: @id.to_i} %>")
$('#amount_product').html(<%= amount_product %>)

app/views/carts/destroy.js.erb
<% if session[:cart].empty? %>
    $('#cart').html('<%= j render 'carts/empty_cart' %>')
<% else %>
    $('#cart-item-<%= @id %>' ).hide();
<% end %>

$('#amount_product').html(<%= amount_product %>)

app/views/carts/index.html.erb
<div class="row" id="cart">
  <% if @products.empty?  %>
    <%= render "carts/empty_cart" %>
  <% else %>
    <div class="col-lg-9">
      <table class="table shadow">
        <thead class="thead-light">
          <tr>
            <th scope="col"><%= t ".image" %></th>
            <th scope="col"><%= t ".product" %></th>
            <th scope="col"><%= t ".price" %></th>
            <th scope="col"><%= t ".quantity" %></th>
            <th scope="col"><%= t ".sum" %></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: "product", collection: @products %>
        </tbody>
      </table>
    </div>
    <div class="col-lg-3 shadow pb-1">
      <h2><%= t ".cart_sumary" %></h2>

      <div class="mb-2 mt-2 horizontal-line"></div>

      <p><%= t ".amount" %>: <span id="cart-sumary-amount"><%= amount_product %></span></p>
      <p><%= t ".total" %>: <span id="total"><%= format_currency @total %></span></p>
      <%= link_to t(".checkout"), new_order_path, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<%= javascript_pack_tag "handle_update_quantity" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DnOe45Ecomerces</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= render "shared/rails_default" %>
  </head>

  <body>
    <div class="app container-fluid">
      <%= render "shared/header" %>
      <main class="app__main">
        <div class="container">
          <div id="flash-messages">
            <%= render "shared/flash" %>
          </div>
          <%= yield %>
        </div>
      </main>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/orders/new.html.erb
<div class="row">
  <div class="col-md-4 order-md-2 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
      <span class="text-muted"><%= t ".your_cart" %></span>
    </h4>
    <ul class="list-group mb-3">
      <% @products.each do |product| %>
        <% id, name, price = product.values_at :id, :name, :price %>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <h6 class="my-0"><%= name %> x <span class="badge badge-info"> <%= session[:cart][id.to_s] %></span></h6>
          <span class="text-muted"><%= format_currency price * session[:cart][id.to_s] %></span>
        </li>
      <% end %>
      <li class="list-group-item d-flex justify-content-between lh-condensed">
        <h6 class="my-0"><%= t ".ship_cost" %></h6>
        <span class="text-muted">$0</span>
      </li>
      <li class="list-group-item d-flex justify-content-between">
        <span><%= t ".total" %></span>
        <strong><%= format_currency @total %></strong>
      </li>
    </ul>
  </div>

  <div class="col-md-8 order-md-1">
    <h4 class="mb-3"><%= t ".your_order" %></h4>
    <%= form_with url: orders_path, class: "needs-validation", html: { novalidate: true } do |form| %>
      <% first_name, last_name, email, address, phone = current_user.values_at :first_name, :last_name, :email, :address, :phone %>
      <div class="row">
        <div class="col-md-6 mb-3">
          <%= form.label :first_name, t(".first_name") %>
          <%= form.text_field :first_name, class: "form-control", readonly: true, value: first_name %>
        </div>
        <div class="col-md-6 mb-3">
          <%= form.label :last_name, t(".last_name") %>
          <%= form.text_field :last_name, class: "form-control", readonly: true, value: last_name %>
        </div>
      </div>

      <div class="mb-3">
        <%= form.label :email, "Email" %>
        <%= form.email_field :email, class: "form-control", placeholder: "emaiexample.com", readonly: true, value: email %>
      </div>

      <div class="mb-3">
        <%= form.label :phone, t(".phone") %>
        <%= form.text_field :phone, class: "form-control", readonly: true, value: phone %>
      </div>

      <div class="mb-3">
        <%= form.label :address, t(".address") %>
        <%= form.text_field :address, class: "form-control", readonly: true, value: address %>
      </div>

      <div class="form-check mb-3">
        <%= form.label :another_address, {"data-toggle":"collapse", "data-target": "#options", "aria-controls": "options", "aria-expanded": false}  do %>
          <%= form.check_box :another_address, class: "form-check-input" %>
          <%= t ".another_address" %>
        <% end %>
        <div id="options" class="collapse">
          <div class="mb-3">
            <%= form.label :name_receive, t(".name_receive") %>
            <%= form.text_field :name_receive, class: "form-control",  required: true %>
          </div>
          <div class="mb-3">
            <%= form.label :address_receive, t(".address_receive") %>
            <%= form.text_field :address_receive, class: "form-control", required: true %>
          </div>
          <div class="mb-3">
            <%= form.label :phone_recieve, t(".phone") %>
            <%= form.text_field :phone_recieve, class: "form-control", required: true %>
          </div>
        </div>
      </div>
      <div class="mb-3">
        <%= form.label :note, t(".note") %>
        <%= form.text_area :note, rows: 3, class: "form-control" %>
      </div>

      <hr class="mb-4">

      <h4 class="mb-3"><%= t ".method_payment" %></h4>

      <div class="d-block my-3">
        <div class="custom-control custom-radio">
          <input id="cod" name="paymentMethod" type="radio" class="custom-control-input" checked required>
          <label class="custom-control-label" for="paypal"><%= t ".cod" %></label>
        </div>
        <div class="custom-control custom-radio">
          <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" required>
          <label class="custom-control-label" for="credit"><%= t ".credit_card" %></label>
        </div>
        <div class="custom-control custom-radio">
          <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required>
          <label class="custom-control-label" for="debit"><%= t ".debit_card" %></label>
        </div>
        <div class="custom-control custom-radio">
          <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>
          <label class="custom-control-label" for="paypal">Paypal</label>
        </div>
      </div>
      <%= form.submit  t(".confirm_order"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/products/_product.html.erb
<div class="col-3 mb-2">
  <div class="card h-100 shadow">
    <%= image_tag "https://picsum.photos/200", alt: "product image", class: "card-img-top"  %>
  <div class="card-body">
    <h5 class="card-title"><%= product.name %></h5>
    <p class="card-tetxt"><%= number_to_currency product.price, precision: 0 %></p>
    <%= link_to t(".detail"), product_path(product), class: "btn btn-primary stretched-link shadow" %>
  </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="row">
  <% if @products.any? %>
    <%= render @products %>
  <% else %>
    <h2><%= t ".no_product_found" %></h2>
  <% end %>
</div>
<%= will_paginate @products if @products.any? %>

app/views/products/show.html.erb
<div class="row">
  <div class="col-lg-4">
    <%= image_tag("https://picsum.photos/200/300", {
        alt: "product image",
        class: "card-img-top img-fluid w-200"
      })
    %>
  </div>
  <div class="col-lg-8">
    <h1><%= @product.name.upcase %></h1>
    <p>
      Price:
      <strong> <%= format_currency @product.price %> </strong>
    </p>
    <% if product_empty @product %>
      <h4><%= t ".out_of_stock" %></h4>
    <% end %>
    <div class="horizontal-line mb-4 mt-4"></div>
    <p><%= @product.description %></p>

    <% unless product_empty @product %>
      <div id="nav-buttons">
        <%= render partial: "carts/add_to_cart", locals: {product: @product} %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <% case type %>
  <% when "error" %>
    <div class="alert alert-danger shadow"><%= message %></div>
  <% when "alert" %>
    <div class="alert alert-warning shadow"><%= message %></div>
  <% when "notice" %>
    <div class="alert alert-success shadow"><%= message %></div>
  <% else %>
    <div class="alert alert-secondary shadow"><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="app__footer text-center horizontal-line">
  <p><%= raw t(".copyright", name: link_to("thevan96", "#")) %></p>
</footer>

app/views/shared/_header.html.erb
<header class="app__header">
  <nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
    <div class="container">
      <%= link_to "Neotech", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul id="navbarNav" class="navbar-nav navbar-collapese ml-auto">
          <li clas="nav-item">
            <%= link_to carts_path, class: "nav-link" do %>
              <i class="fas fa-shopping-cart mr-1"></i><sup id="amount_product"><%= amount_product %></sup>
            <% end %>
          </li>
          <% if logged_in? %>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle"
                type="button"
                id="dropdownMenuButton"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false">
                <%= @current_user.first_name %>
              </button>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                <li><%= link_to t(".profile"), "#", class: "dropdown-item" %></li>
                <li><%= link_to t(".settings"), "#", class: "dropdown-item" %></li>
                <li class="dropdown-divider"></li>
                <li>
                  <%= link_to t(".sign_out"), sign_out_path, method: :delete,
                    class: "dropdown-item" %>
                </li>
              </div>
            </div>
          <% else %>
            <li class="nav-item">
              <%= link_to t(".sign_in"), sign_in_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", {
  media: "all",
  "data-turbolinks-track": "reload"
} %>
<%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

app/views/static_pages/home.html.erb
<h1>Home page</h1>